config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens}
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @kitten}
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten submitted"
      redirect_to @kitten
    else
      flash.now[:failure] = "Invalid Parameters"
      render 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten updated"
      redirect_to @kitten
    else
      flash.now[:failure] = "Invalid Parameters"
      render 'edit'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:success] = "Kitten DESTROYED"
    redirect_to root_path
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for @kitten do |f| %>
	<%= f.label :name, "Name:" %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :age, "Age:" %>
	<%= f.number_field :age, in: 0..40, step: 1 %>
	<br>
	<%= f.label :cuteness, "Cuteness:" %>
	<%= f.number_field :cuteness, in: 0..10, step: 1 %>
	<br>
	<%= f.label :softness, "Softness:" %>
	<%= f.number_field :softness, in: 0..10, step: 1 %>
	<br>
	<%= f.submit %>
<% end %>

app/views/kittens/_kitten.html.erb
<%= kitten.name %><br>
<%= kitten.age %> age<br>
<%= kitten.cuteness %> cuteness<br>
<%= kitten.softness %> softness<br>
<%= link_to "Destroy", kitten_path(kitten), method: :delete %>
<hr>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render 'form' %>

<%= link_to "Destroy", kitten_path, method: :delete %>

app/views/kittens/index.html.erb
Index
<hr>
<%= render @kittens %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render 'form' %>

app/views/kittens/show.html.erb
<%= @kitten.name %><br>
<%= @kitten.age %> age<br>
<%= @kitten.cuteness %> cuteness<br>
<%= @kitten.softness %> softness<br>

<%= link_to "Destroy", kitten_path, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </body>
</html>